# Application Configuration
quarkus.application.name=pokemon-duels
quarkus.http.port=8881
app.pokemon-duels.timezone=${APP_POKEMON_DUELS_TIMEZONE:America/Sao_Paulo}

# MongoDB Configuration
quarkus.mongodb.connection-string=${DBAAS_MONGODB_ENDPOINT:mongodb://localhost:27017}
quarkus.mongodb.database=${DBAAS_MONGODB_DBNAME:pokemon-duels}

# PokeAPI REST client
quarkus.rest-client.pokeapi.url=https://pokeapi.co/api/v2

# Swagger / OpenAPI Configuration
quarkus.swagger-ui.title=Pokemon Duels API Documentation
quarkus.smallrye-openapi.info-title=Pokemon Duels API Documentation
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.swagger-ui.theme=muted
quarkus.swagger-ui.try-it-out-enabled=true
quarkus.swagger-ui.persist-authorization=true
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui

